## Kitty Configuration

## Cursor
cursor_blink_interval       0.55
cursor_shape                beam
cursor_trail                1
cursor_beam_thickness       1.5
cursor_trail_decay          0.1 0.4
cursor_underline_thickness  0.15

# Scrolling
touchpad_scroll_multiplier  1.0
wheel_scroll_multiplier     1.0

## Window
background_opacity          0.70
background_blur             1

window_padding_width        15
background                  #1a1b26

## Fonts
font_family                 JetBrainsMono Nerd Font
font_size                   14.0
