## Kitty Configuration

## Cursor
cursor_blink_interval       0.55
cursor_shape                block
cursor_beam_thickness       0.15
cursor_underline_thickness  0.15

# Scrolling
touchpad_scroll_multiplier  1.0
wheel_scroll_multiplier     1.0

## Window
window_opacity              0.8
window_padding_width        15
background                  #1a1b26

## Fonts
font_family                 JetBrainsMono Nerd Font
font_size                   14.0
